org.gradle.jvmargs=-Xmx2048m -Dhttp.socketTimeout=120000 -Dhttp.connectionTimeout=120000
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.paths=C:/Program Files/Microsoft/jdk-17.0.20.8-hotspot
org.gradle.java.home=C:/Program Files/Microsoft/jdk-17.0.20.8-hotspot
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# Disable built-in Kotlin support so the explicit Kotlin plugin can be used.
android.builtInKotlin=false
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
