from pathlib import Path

lines = []
lines.append("rules_version = '2';")
lines.append("")
lines.append("service cloud.firestore {")
lines.append("  match /databases/{database}/documents {")
lines.append("")
lines.append("    function isSignedIn() {")
lines.append("      return request.auth != null;")
lines.append("    }")
lines.append("")
lines.append("    function isOwner(uid) {")
lines.append("      return isSignedIn() && request.auth.uid == uid;")
lines.append("    }")
lines.append("")
lines.append("    match /users/{uid} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isOwner(uid);")
lines.append("      allow update: if isOwner(uid);")
lines.append("      allow delete: if isOwner(uid);")
lines.append("    }")
lines.append("")
lines.append("    match /profiles/{uid} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isOwner(uid);")
lines.append("      allow update: if isOwner(uid);")
lines.append("      allow delete: if isOwner(uid);")
lines.append("    }")
lines.append("")
lines.append("    match /groups/{groupId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isSignedIn();")
lines.append("      allow update: if isSignedIn();")
lines.append("      allow delete: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /groups/{groupId}/members/{memberId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isSignedIn();")
lines.append("      allow update: if isSignedIn();")
lines.append("      allow delete: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /conversations/{conversationId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isSignedIn();")
lines.append("      allow update: if isSignedIn();")
lines.append("      allow delete: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /messages/{messageId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isSignedIn();")
lines.append("      allow update: if isSignedIn();")
lines.append("      allow delete: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /calls/{callId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isSignedIn();")
lines.append("      allow update: if isSignedIn();")
lines.append("      allow delete: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /notifications/{notificationId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isSignedIn();")
lines.append("      allow update: if isSignedIn();")
lines.append("      allow delete: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /tokenTransactions/{transactionId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isSignedIn();")
lines.append("      allow update: if isSignedIn();")
lines.append("      allow delete: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /supportTickets/{ticketId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow create: if isSignedIn();")
lines.append("      allow update: if isSignedIn();")
lines.append("      allow delete: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /appConfig/{configId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow write: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /systemLogs/{logId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow write: if isSignedIn();")
lines.append("    }")
lines.append("")
lines.append("    match /featureFlags/{flagId} {")
lines.append("      allow read: if isSignedIn();")
lines.append("      allow write: if isSignedIn();")
lines.append("    }")
lines.append("")

for i in range(1, 161):
    name = f"collection_{i:03d}"
    lines.append(f"    // Rule block for {name}")
    lines.append(f"    match /{name}/{{docId}} {{")
    lines.append("      allow read: if isSignedIn();")
    lines.append("      allow create: if isSignedIn();")
    lines.append("      allow update: if isSignedIn();")
    lines.append("      allow delete: if isSignedIn();")
    lines.append("    }")
    lines.append("")
    lines.append(f"    match /{name}/{{docId}}/messages/{{messageId}} {{")
    lines.append("      allow read: if isSignedIn();")
    lines.append("      allow create: if isSignedIn();")
    lines.append("      allow update: if isSignedIn();")
    lines.append("      allow delete: if isSignedIn();")
    lines.append("    }")
    lines.append("")
    lines.append(f"    match /{name}/{{docId}}/threads/{{threadId}} {{")
    lines.append("      allow read: if isSignedIn();")
    lines.append("      allow create: if isSignedIn();")
    lines.append("      allow update: if isSignedIn();")
    lines.append("      allow delete: if isSignedIn();")
    lines.append("    }")
    lines.append("")
    lines.append(f"    match /{name}/{{docId}}/replies/{{replyId}} {{")
    lines.append("      allow read: if isSignedIn();")
    lines.append("      allow create: if isSignedIn();")
    lines.append("      allow update: if isSignedIn();")
    lines.append("      allow delete: if isSignedIn();")
    lines.append("    }")
    lines.append("")

lines.append("  }")
lines.append("}")

Path("firestore.rules").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {len(lines)} lines")
